// This file is generated by scripts/generate-tag-icons.mjs.
// Do not edit it manually.
import { faBookmark as faBookmarkRegular } from '@fortawesome/free-regular-svg-icons/faBookmark'
import { faHeart as faHeartRegular } from '@fortawesome/free-regular-svg-icons/faHeart'
import { faStar as faStarRegular } from '@fortawesome/free-regular-svg-icons/faStar'
import { faThumbsDown as faThumbsDownRegular } from '@fortawesome/free-regular-svg-icons/faThumbsDown'
import { faThumbsUp as faThumbsUpRegular } from '@fortawesome/free-regular-svg-icons/faThumbsUp'
import type { IconDefinition } from '@fortawesome/free-solid-svg-icons'
import { faAngleDown } from '@fortawesome/free-solid-svg-icons/faAngleDown'
import { faAngleLeft } from '@fortawesome/free-solid-svg-icons/faAngleLeft'
import { faAngleRight } from '@fortawesome/free-solid-svg-icons/faAngleRight'
import { faAnglesDown } from '@fortawesome/free-solid-svg-icons/faAnglesDown'
import { faAnglesLeft } from '@fortawesome/free-solid-svg-icons/faAnglesLeft'
import { faAnglesRight } from '@fortawesome/free-solid-svg-icons/faAnglesRight'
import { faAnglesUp } from '@fortawesome/free-solid-svg-icons/faAnglesUp'
import { faAngleUp } from '@fortawesome/free-solid-svg-icons/faAngleUp'
import { faArrowDown } from '@fortawesome/free-solid-svg-icons/faArrowDown'
import { faArrowDown19 } from '@fortawesome/free-solid-svg-icons/faArrowDown19'
import { faArrowDown91 } from '@fortawesome/free-solid-svg-icons/faArrowDown91'
import { faArrowDownAZ } from '@fortawesome/free-solid-svg-icons/faArrowDownAZ'
import { faArrowDownShortWide } from '@fortawesome/free-solid-svg-icons/faArrowDownShortWide'
import { faArrowDownWideShort } from '@fortawesome/free-solid-svg-icons/faArrowDownWideShort'
import { faArrowDownZA } from '@fortawesome/free-solid-svg-icons/faArrowDownZA'
import { faArrowLeft } from '@fortawesome/free-solid-svg-icons/faArrowLeft'
import { faArrowRight } from '@fortawesome/free-solid-svg-icons/faArrowRight'
import { faArrowsLeftRight } from '@fortawesome/free-solid-svg-icons/faArrowsLeftRight'
import { faArrowsUpDown } from '@fortawesome/free-solid-svg-icons/faArrowsUpDown'
import { faArrowUp } from '@fortawesome/free-solid-svg-icons/faArrowUp'
import { faArrowUp19 } from '@fortawesome/free-solid-svg-icons/faArrowUp19'
import { faArrowUp91 } from '@fortawesome/free-solid-svg-icons/faArrowUp91'
import { faArrowUpAZ } from '@fortawesome/free-solid-svg-icons/faArrowUpAZ'
import { faArrowUpShortWide } from '@fortawesome/free-solid-svg-icons/faArrowUpShortWide'
import { faArrowUpWideShort } from '@fortawesome/free-solid-svg-icons/faArrowUpWideShort'
import { faArrowUpZA } from '@fortawesome/free-solid-svg-icons/faArrowUpZA'
import { faAward } from '@fortawesome/free-solid-svg-icons/faAward'
import { faBell } from '@fortawesome/free-solid-svg-icons/faBell'
import { faBellSlash } from '@fortawesome/free-solid-svg-icons/faBellSlash'
import { faBook } from '@fortawesome/free-solid-svg-icons/faBook'
import { faBookmark } from '@fortawesome/free-solid-svg-icons/faBookmark'
import { faBroom } from '@fortawesome/free-solid-svg-icons/faBroom'
import { faCheck } from '@fortawesome/free-solid-svg-icons/faCheck'
import { faClock } from '@fortawesome/free-solid-svg-icons/faClock'
import { faComment } from '@fortawesome/free-solid-svg-icons/faComment'
import { faCrown } from '@fortawesome/free-solid-svg-icons/faCrown'
import { faEdit } from '@fortawesome/free-solid-svg-icons/faEdit'
import { faEnvelope } from '@fortawesome/free-solid-svg-icons/faEnvelope'
import { faEnvelopeOpen } from '@fortawesome/free-solid-svg-icons/faEnvelopeOpen'
import { faFilter } from '@fortawesome/free-solid-svg-icons/faFilter'
import { faGlobe } from '@fortawesome/free-solid-svg-icons/faGlobe'
import { faHand } from '@fortawesome/free-solid-svg-icons/faHand'
import { faHeart } from '@fortawesome/free-solid-svg-icons/faHeart'
import { faIceCream } from '@fortawesome/free-solid-svg-icons/faIceCream'
import { faLock } from '@fortawesome/free-solid-svg-icons/faLock'
import { faMedal } from '@fortawesome/free-solid-svg-icons/faMedal'
import { faMessage } from '@fortawesome/free-solid-svg-icons/faMessage'
import { faMinus } from '@fortawesome/free-solid-svg-icons/faMinus'
import { faPlus } from '@fortawesome/free-solid-svg-icons/faPlus'
import { faQuestion } from '@fortawesome/free-solid-svg-icons/faQuestion'
import { faReply } from '@fortawesome/free-solid-svg-icons/faReply'
import { faScissors } from '@fortawesome/free-solid-svg-icons/faScissors'
import { faSearch } from '@fortawesome/free-solid-svg-icons/faSearch'
import { faShuffle } from '@fortawesome/free-solid-svg-icons/faShuffle'
import { faSort } from '@fortawesome/free-solid-svg-icons/faSort'
import { faSortDown } from '@fortawesome/free-solid-svg-icons/faSortDown'
import { faSortUp } from '@fortawesome/free-solid-svg-icons/faSortUp'
import { faStar } from '@fortawesome/free-solid-svg-icons/faStar'
import { faStarHalf } from '@fortawesome/free-solid-svg-icons/faStarHalf'
import { faStopwatch } from '@fortawesome/free-solid-svg-icons/faStopwatch'
import { faTag } from '@fortawesome/free-solid-svg-icons/faTag'
import { faThumbsDown } from '@fortawesome/free-solid-svg-icons/faThumbsDown'
import { faThumbsUp } from '@fortawesome/free-solid-svg-icons/faThumbsUp'
import { faTrophy } from '@fortawesome/free-solid-svg-icons/faTrophy'
import { faUnlock } from '@fortawesome/free-solid-svg-icons/faUnlock'
import { faUser } from '@fortawesome/free-solid-svg-icons/faUser'
import { faWarning } from '@fortawesome/free-solid-svg-icons/faWarning'
import { faXmark } from '@fortawesome/free-solid-svg-icons/faXmark'

const tagIconDefinitions: Record<string, IconDefinition> = {
    AngleDown: faAngleDown,
    AngleLeft: faAngleLeft,
    AngleRight: faAngleRight,
    AngleUp: faAngleUp,
    AnglesDown: faAnglesDown,
    AnglesLeft: faAnglesLeft,
    AnglesRight: faAnglesRight,
    AnglesUp: faAnglesUp,
    ArrowDown: faArrowDown,
    ArrowLeft: faArrowLeft,
    ArrowRight: faArrowRight,
    ArrowUp: faArrowUp,
    ArrowsLeftRight: faArrowsLeftRight,
    ArrowsUpDown: faArrowsUpDown,
    Award: faAward,
    Bell: faBell,
    BellSlash: faBellSlash,
    Book: faBook,
    Bookmark: faBookmark,
    BookmarkHollow: faBookmarkRegular,
    Broom: faBroom,
    Check: faCheck,
    Clock: faClock,
    Comment: faComment,
    Crown: faCrown,
    Edit: faEdit,
    Envelope: faEnvelope,
    EnvelopeOpen: faEnvelopeOpen,
    Filter: faFilter,
    Globe: faGlobe,
    Hand: faHand,
    Heart: faHeart,
    HeartHollow: faHeartRegular,
    IceCream: faIceCream,
    Lock: faLock,
    Medal: faMedal,
    Message: faMessage,
    Minus: faMinus,
    Plus: faPlus,
    Question: faQuestion,
    Reply: faReply,
    Scissors: faScissors,
    Search: faSearch,
    Shuffle: faShuffle,
    Sort: faSort,
    SortDown: faSortDown,
    SortDown19: faArrowDown19,
    SortDown91: faArrowDown91,
    SortDownAZ: faArrowDownAZ,
    SortDownShortWide: faArrowDownShortWide,
    SortDownWideShort: faArrowDownWideShort,
    SortDownZA: faArrowDownZA,
    SortUp: faSortUp,
    SortUp19: faArrowUp19,
    SortUp91: faArrowUp91,
    SortUpAZ: faArrowUpAZ,
    SortUpShortWide: faArrowUpShortWide,
    SortUpWideShort: faArrowUpWideShort,
    SortUpZA: faArrowUpZA,
    Star: faStar,
    StarHalf: faStarHalf,
    StarHollow: faStarRegular,
    Stopwatch: faStopwatch,
    Tag: faTag,
    ThumbsDown: faThumbsDown,
    ThumbsDownHollow: faThumbsDownRegular,
    ThumbsUp: faThumbsUp,
    ThumbsUpHollow: faThumbsUpRegular,
    Trophy: faTrophy,
    Unlock: faUnlock,
    User: faUser,
    Warning: faWarning,
    XMark: faXmark,
}

export function resolveTagIcon(key: string) {
    return tagIconDefinitions[key]
}
